pluginGroup=com.touchkiss.pastetomd
pluginName=Paste to Markdown
pluginVersion=0.1.0
pluginSinceBuild=262
localIdePath=/Applications/IntelliJ IDEA.app
platformBundledPlugins=org.intellij.plugins.markdown
gradleVersion=9.7.1
org.gradle.java.home=/Users/liushiyou/.sdkman/candidates/java/25.0.2-oracle
javaVersion=25
kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=true
org.gradle.caching=true

